name: Convert Report to PDF

on:
  workflow_dispatch:
    inputs:
      report:
        description: 'Report to update'
        required: true
        type: choice
        options:
        - Aciclovir-Mean
        - Aciclovir-Mean-SVG
  
jobs:
  convert:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: install pagedjs
      run: |
        npm install -g pagedjs-cli
    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@v2
    - name: Perform html conversion with pandoc
      run: |
        pandoc -f markdown -t html5 --embed-resources --standalone \
          --pdf-engine=pagedjs-cli \
          -o Reports/${{ inputs.report }}/Report.pdf Reports/${{ inputs.report }}/Report.md -c osp.css
    - name: Save PDF file as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.report }}-pdf
        path: ./Reports/${{ inputs.report }}
