name: Convert Report to PDF

on:
  workflow_dispatch:
  
jobs:
  report-to-pdf:
    runs-on: ubuntu-latest
    # Allow only authorized collaborators to trigger GA:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
# All steps in workflow:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Perform html conversion with pandoc
        run: |
          for file in $(find . -name "*.md"); do
            pandoc -f markdown -t html5 --embed-resources --standalone \
            -o ${file%.md}.html $file -c osp.css
          done
        
      # Run the HTML to PDF converter action
      - name: HTML website to PDF converter
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./Reports/*/Report.html
          outputFile: ./Reports/*/Report.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}, "displayHeaderFooter": true, "headerTemplate": "<span></span>", "footerTemplate": "<span style=\"font-size: 12px;\">&emsp;&emsp;Page <span class=\"pageNumber\"></span> / <span class=\"totalPages\"></span></span>"}'
          
      - name: Save PDF file as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-pdf
          path: ./Reports
